library(here)

here::i_am("code/awcLIDAR_master.R")

# nse outside modeling
source(here("code", "awcLIDAR_match.R"))
source(here("code", "awcLIDAR_area.R"))   
  # requires z to be generated by awcLIDAR_match